site_name: MIxS-MInAS
site_url: https://mixs-minas.org/
nav:
  - Home: index.md
  - Proposal: proposal.md
  - Project Phases: phases.md
  - Drafts:
      - drafts/index.md
      - "Ancient Extension": drafts/ancient-extension.md
      - "MIxS Term Updates": drafts/existing-term-updates.md
      - "MInAS Submission Packages": drafts/minas-submission-packages.md
      - "Deprecated": drafts/draft.md
  - Contributors: contributors.md
theme:
  name: material
  font:
    text: Albert Sans
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
  - table-reader
  - section-index
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
extra:
  consent:
    title: Cookie consent
    description: >-
      This website uses cookies to improve your experience. We'll assume you're ok with this, but you can opt-out if you wish
    actions:
      - accept
      - reject
